# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: just-fmt
        name: just fmt
        description: Format and lint code
        entry: just fmt
        language: system
        types_or: [rust, ts]
        pass_filenames: false

      - id: just-typecheck
        name: just typecheck
        description: TypeScript type checking across all workspaces
        entry: just typecheck
        language: system
        types_or: [ts]
        pass_filenames: false
